# Site Settings
baseurl: ""
url: "https://ephraim.github.io"

# Blog Settings
theme_settings:
  title: Duncan's Theme
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/smile.png
    username: Ephraim Atta-Duncan
    description: Programmer💻 Mars🌕
    experience:
      - start: 2018-12-12
        end: Current
        experience: Started Programming, Coder
      - start: 2017-05-03
        end: Current
        experience: Started Photoshop, Baby Designer
    skills:
      - skill: HTML5 & CSS
        value: 80 # Percent value
      - skill: Python
        value: 60 # Percent value
      - skill: JavScript
        value: 40 # Percent value
      - skill: React and Vue
        value: 45 # Percent value
      - skill: Sass
        value: 90 # Percent value
      - skill: Adobe Photoshop
        value: 70 # Percent value

  # Icons
  icons:
    email: ephraimduncan68@gmail.com
    linkedin:
    github: ephraimduncan
    gitlab:
    bitbucket:
    google_plus:
    twitter: duncan___e
    youtube: Duncan Multimedia
    facebook:
    instagram: duncan.am.i

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
